export const ALL_USERS = 'ALL_USERS';
export const ALL_REQUESTS = 'ALL_REQUESTS';
export const ALL_PENDING_REQUESTS = 'ALL_PENDING_REQUESTS';
export const ALL_WALLETS = 'ALL_WALLETS';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';